# Generated by Django 5.1.1 on 2024-09-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('charges', models.IntegerField(default='Free')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('Corruption', 'Corruption'), ('Accident', 'Accident'), ('Harassment', 'Harassment'), ('Sexual Abuse', 'Sexual Abuse'), ('Discrimination', 'Discrimination'), ('Domestic Violence', 'Domestic Violence'), ('Child Abuse', 'Child Abuse'), ('Fraud', 'Fraud'), ('Workplace Misconduct', 'Workplace Misconduct'), ('Cyber Crime', 'Cyber Crime'), ('Human Trafficking', 'Human Trafficking'), ('Environmental Crime', 'Environmental Crime'), ('Bullying', 'Bullying'), ('Police Brutality', 'Police Brutality'), ('Drug Trafficking', 'Drug Trafficking'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.authority'),
        ),
    ]
