# Generated by Django 5.1.1 on 2024-09-27 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_case_tracked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='tracked_by',
        ),
        migrations.AddField(
            model_name='case',
            name='tracked_by',
            field=models.ManyToManyField(blank=True, related_name='tracked_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
