# Generated by Django 5.1.1 on 2024-09-27 23:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_case_tracked_by_case_tracked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority',
            name='years_of_experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('Corruption', 'Corruption'), ('Accident', 'Accident'), ('Harassment', 'Harassment'), ('Sexual Abuse', 'Sexual Abuse'), ('Discrimination', 'Discrimination'), ('Domestic Violence', 'Domestic Violence'), ('Child Abuse', 'Child Abuse'), ('Fraud', 'Fraud'), ('Workplace Misconduct', 'Workplace Misconduct'), ('Cyber Crime', 'Cyber Crime'), ('Human Trafficking', 'Human Trafficking'), ('Environmental Crime', 'Environmental Crime'), ('Bullying', 'Bullying'), ('Police Brutality', 'Police Brutality'), ('Drug Trafficking', 'Drug Trafficking'), ('Land Dispute', 'Land Dispute'), ('Tax Evasion', 'Tax Evasion'), ('Identity Theft', 'Identity Theft'), ('Property Damage', 'Property Damage'), ('Fraudulent Financial Institution', 'Fraudulent Financial Institution'), ('Terrorism', 'Terrorism'), ('Vandalism', 'Vandalism'), ('Other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='home.authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lawyer')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
